remote: origin
target-branch: master
helm-extra-args: --timeout 600s
chart-dirs:
  - charts/incubator
  - charts/stable
chart-repos:
  - homelab-ci-libraries=https://homelab-ci.gitlab.io/library-ezUxewsl
